# Generated by Django 5.1.1 on 2024-09-11 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('content', models.TextField(verbose_name='Course content')),
                ('author', models.URLField(verbose_name='call link')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of creation')),
                ('show_home', models.BooleanField(default=False, verbose_name='Show at home')),
            ],
        ),
    ]
