# Generated by Django 5.1.1 on 2024-09-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='call',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Course title'),
        ),
    ]
