# Generated by Django 5.1.1 on 2024-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_author_course_call_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_list',
            field=models.FileField(null=True, upload_to='courses/list/', verbose_name='listed content'),
        ),
    ]
