# Generated by Django 5.1.1 on 2024-09-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_content_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='cover'),
        ),
    ]
