# Generated by Django 5.1.1 on 2024-09-15 03:12

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='cover'),
        ),
    ]
