# Generated by Django 5.1.1 on 2024-09-15 03:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Course content'),
        ),
    ]
