# Generated by Django 5.1.1 on 2024-09-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
