# Generated by Django 5.1.1 on 2024-09-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='¿Has been contacted?'),
        ),
    ]
