# Generated by Django 5.1.1 on 2024-09-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_alter_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='lastname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=15, verbose_name='password1')),
                ('password2', models.CharField(max_length=15, verbose_name='password1')),
            ],
        ),
    ]
